export const title = "UFCV"
export const subTitle = "Dynamiser son pfojet professionnel"
export const navHome = "Accueil"
export const navGallery = "Gallery"
export const footerLabel = "UFCV Footer"