export const title = "On y va!"
export const subTitle = "Découvrir des personnes qui étudient le français"
export const navHome = "Accueil"
export const navGallery = "Gallery"
export const footerLabel = "On y va!"